# Generated by Django 2.2 on 2019-04-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('event_status_id', models.IntegerField()),
                ('place', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('deadline_date', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
