# Generated by Django 2.2 on 2019-04-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190414_1604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='event',
        ),
        migrations.RemoveField(
            model_name='event_status',
            name='id',
        ),
        migrations.AlterField(
            model_name='event_status',
            name='event_status_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event_status',
            name='event_status_name',
            field=models.TextField(max_length=200),
        ),
    ]
