# Generated by Django 2.2 on 2019-04-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.BigIntegerField()),
                ('event_name', models.CharField(max_length=200)),
                ('owner_id', models.BigIntegerField()),
                ('event_status_id', models.IntegerField()),
                ('place', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('deadline_date', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='event_statuses',
            new_name='event_status',
        ),
        migrations.DeleteModel(
            name='events',
        ),
    ]
