# Generated by Django 2.2 on 2019-04-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190414_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.BigIntegerField()),
                ('event_name', models.CharField(max_length=200)),
                ('owner_id', models.BigIntegerField()),
                ('event_status_id', models.BigIntegerField()),
                ('place', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('deadline_date', models.DateField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
